#===============================================================================
#
#  M A I N . Y M L
#
#===============================================================================
- hosts: all
  gather_facts: true
  roles:
  - role: homebrew
